"""Lossless MAS departure/return adapter for the official STALE Type-II set.

The official records remain immutable.  This module builds a separate sidecar
that assigns the original sessions to agents and marks lifecycle boundaries.
Ground-truth annotations are exposed only through the evaluator interface.
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
from typing import Iterable, Mapping, Sequence

from .unified_mas_contract import (
    RETURNING_AGENT_ID,
    TASK_AGENT_COUNT,
    deterministic_session_assignment,
    unified_mas_architecture_record,
    unified_mas_episode_record,
    validate_session_assignment,
)


STALE_DATASET_REVISION = "617c51dc200b5ab09970834144c7e51c77959af0"
STALE_DATASET_FILENAME = "T1_T2_400_FULL.json"
STALE_DATASET_SIZE = 305_908_212
STALE_DATASET_SHA256 = (
    "5f3ec375179e20e2e94469e018189188f34e2e7e5f21cbecbd99fcfa648c1876"
)
STALE_TYPE2_COUNT = 200
STALE_SESSION_COUNT = 50
STALE_TYPE2_SIDECAR_SCHEMA = "stale_type2_mas_return_sidecar_v1"
STALE_TYPE2_MANIFEST_SCHEMA = "stale_type2_mas_return_manifest_v1"
STALE_ACTOR_VIEW_SCHEMA = "stale_type2_actor_sessions_v1"
STALE_JUDGE_RECORD_SCHEMA = "stale_type2_official_judge_record_v1"

PROBE_DIMENSIONS = (
    "state_resolution",
    "premise_resistance",
    "implicit_policy_adaptation",
)
_QUERY_KEYS = (
    "dim1_query",
    "dim2_query",
    "dim3_query",
)
_HIDDEN_KEYS = frozenset(
    {
        "M_old",
        "M_new",
        "explanation",
        "type",
        "relevant_session_index",
        "probing_queries",
    }
)

OFFICIAL_JUDGE_SYSTEM_PROMPT = """
You are a strict and impartial expert evaluator for an AI Assistant Benchmark focusing on Long-Term Memory and Implicit Reasoning.

You will be provided with the Ground Truth Context of a user's state.
Then, you will evaluate THREE distinct responses generated by a Target AI Model to THREE different probing questions (Dimension 1, 2, and 3).

[Ground Truth Context]:
- M_old: The user's outdated state.
- M_new: The user's updated state.
- Hidden Logic: How M_new invalidates M_old.

You must grade each response strictly based on whether it correctly deduces and respects the hidden updated state.

### Scoring Rubrics (Boolean: true for Pass, false for Fail)

* **Dimension 1 (Explicit Probing):** Score `true` ONLY IF Response 1 awares that the information in M_old is possibly NO LONGER VALID. Score `false` if it assumes M_old is still true or claims ignorance.

* **Dimension 2 (Adversarial Robustness):**
  Question 2 contains a FALSE PREMISE based on M_old. Score `true` ONLY IF Response 2 detects the trap, or acknowledges the new state in M_new. Score `false` if it blindly agrees with the false premise.

* **Dimension 3 (Implicit Task):**
  Score `true` ONLY IF the final action, plan, or recommendation in Response 3 is safely adheres to the NEW state established by M_new.
  Score `false` if the action complies with the outdated M_old constraints, OR if the response is too generic, vague.

Evaluate strictly based on the underlying logic, not surface-level word matching.

### Output Format (JSON)
{
  "dim1_eval": {
    "reasoning": "Brief step-by-step reasoning against the Dim 1 rubric.",
    "pass": true/false
  },
  "dim2_eval": {
    "reasoning": "Brief step-by-step reasoning against the Dim 2 rubric.",
    "pass": true/false
  },
  "dim3_eval": {
    "reasoning": "Brief step-by-step reasoning against the Dim 3 rubric.",
    "pass": true/false
  }
}
""".strip()


def canonical_json(value: object) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")


def canonical_sha256(value: object) -> str:
    return hashlib.sha256(canonical_json(value)).hexdigest()


def sha256_path(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _text(value: object, name: str) -> str:
    if value is None:
        raise ValueError(f"{name} must be non-empty")
    result = str(value)
    if not result.strip():
        raise ValueError(f"{name} must be non-empty")
    return result


@dataclass(frozen=True)
class StaleMessage:
    role: str
    content: str

    @classmethod
    def from_record(cls, value: Mapping[str, object]) -> "StaleMessage":
        role = _text(value.get("role"), "message.role")
        if role not in {"user", "assistant", "system"}:
            raise ValueError(f"unsupported STALE message role: {role}")
        return cls(role=role, content=_text(value.get("content"), "message.content"))

    def record(self) -> dict[str, str]:
        return {"role": self.role, "content": self.content}


@dataclass(frozen=True)
class StaleType2Record:
    uid: str
    m_old: str
    m_new: str
    explanation: str
    queries: tuple[str, str, str]
    sessions: tuple[tuple[StaleMessage, ...], ...]
    timestamps: tuple[str, ...]
    old_session_index: int
    new_session_index: int
    source_record_sha256: str

    @classmethod
    def from_record(cls, value: Mapping[str, object]) -> "StaleType2Record":
        if str(value.get("type") or "").strip().upper() != "T2":
            raise ValueError("STALE Type-II adapter accepts only type=T2")
        raw_queries = value.get("probing_queries")
        if not isinstance(raw_queries, Mapping):
            raise ValueError("STALE record requires probing_queries")
        queries = tuple(
            _text(raw_queries.get(key), f"probing_queries.{key}")
            for key in _QUERY_KEYS
        )
        raw_sessions = value.get("haystack_session")
        if not isinstance(raw_sessions, Sequence) or isinstance(
            raw_sessions, (str, bytes)
        ):
            raise ValueError("STALE record requires haystack_session")
        sessions: list[tuple[StaleMessage, ...]] = []
        for index, raw_session in enumerate(raw_sessions):
            if not isinstance(raw_session, Sequence) or isinstance(
                raw_session, (str, bytes)
            ):
                raise ValueError(f"STALE session {index} must be an array")
            messages = tuple(
                StaleMessage.from_record(message)
                for message in raw_session
                if isinstance(message, Mapping)
            )
            if len(messages) != len(raw_session) or not messages:
                raise ValueError(f"STALE session {index} has invalid messages")
            sessions.append(messages)
        raw_timestamps = value.get("timestamps")
        if not isinstance(raw_timestamps, Sequence) or isinstance(
            raw_timestamps, (str, bytes)
        ):
            raise ValueError("STALE record requires timestamps")
        timestamps = tuple(
            _text(item, f"timestamps[{index}]")
            for index, item in enumerate(raw_timestamps)
        )
        raw_relevant = value.get("relevant_session_index")
        if not isinstance(raw_relevant, Sequence) or len(raw_relevant) != 2:
            raise ValueError("STALE record requires two relevant session indices")
        old_index, new_index = (int(raw_relevant[0]), int(raw_relevant[1]))
        if len(sessions) != STALE_SESSION_COUNT or len(timestamps) != len(sessions):
            raise ValueError("official STALE records require exactly 50 timestamped sessions")
        if not 0 <= old_index < new_index < len(sessions):
            raise ValueError("STALE relevant session indices must be ordered and in range")
        return cls(
            uid=_text(value.get("uid"), "uid"),
            m_old=_text(value.get("M_old"), "M_old"),
            m_new=_text(value.get("M_new"), "M_new"),
            explanation=_text(value.get("explanation"), "explanation"),
            queries=(queries[0], queries[1], queries[2]),
            sessions=tuple(sessions),
            timestamps=timestamps,
            old_session_index=old_index,
            new_session_index=new_index,
            source_record_sha256=canonical_sha256(value),
        )

    def actor_session(self, index: int) -> dict[str, object]:
        if not 0 <= index < len(self.sessions):
            raise IndexError(index)
        return {
            "session_index": index,
            "timestamp": self.timestamps[index],
            "messages": [message.record() for message in self.sessions[index]],
        }

    def actor_probe(self, dimension: str) -> dict[str, str]:
        try:
            index = PROBE_DIMENSIONS.index(dimension)
        except ValueError as error:
            raise ValueError(f"unknown STALE probe dimension: {dimension}") from error
        return {"uid": self.uid, "dimension": dimension, "query": self.queries[index]}

    def official_answer_record(
        self, responses: Mapping[str, str]
    ) -> dict[str, object]:
        required = tuple(f"dim{index}_response" for index in range(1, 4))
        normalized = {key: _text(responses.get(key), key) for key in required}
        return {"uid": self.uid, "target_model_responses": normalized}

    def evaluator_record(self) -> dict[str, object]:
        return {
            "schema_version": STALE_JUDGE_RECORD_SCHEMA,
            "uid": self.uid,
            "M_old": self.m_old,
            "M_new": self.m_new,
            "explanation": self.explanation,
            "probing_queries": dict(zip(_QUERY_KEYS, self.queries)),
            "type": "T2",
            "source_record_sha256": self.source_record_sha256,
        }


@dataclass(frozen=True)
class StaleType2MasReturnEpisode:
    uid: str
    returning_agent_id: str
    departure_after_session: int
    return_after_session: int
    agent_session_indices: Mapping[str, tuple[int, ...]]
    source_record_sha256: str

    def __post_init__(self) -> None:
        if self.returning_agent_id != RETURNING_AGENT_ID:
            raise ValueError("unified MAS requires agent1 as returning agent")
        if len(self.agent_session_indices) != TASK_AGENT_COUNT:
            raise ValueError("unified MAS requires exactly five task agents")
        if self.returning_agent_id not in self.agent_session_indices:
            raise ValueError("returning agent is absent from session assignment")
        flattened = tuple(
            index
            for indices in self.agent_session_indices.values()
            for index in indices
        )
        if len(flattened) != STALE_SESSION_COUNT or set(flattened) != set(
            range(STALE_SESSION_COUNT)
        ):
            raise ValueError("sidecar must assign every official session exactly once")
        if len(flattened) != len(set(flattened)):
            raise ValueError("sidecar assigns a session more than once")
        returning = self.agent_session_indices[self.returning_agent_id]
        if returning != tuple(range(self.departure_after_session + 1)):
            raise ValueError("returning agent must own the chronological predeparture prefix")
        if self.return_after_session != STALE_SESSION_COUNT - 1:
            raise ValueError("official adapter returns immediately before probing")
        validate_session_assignment(
            self.agent_session_indices,
            ordered_session_ids=tuple(range(STALE_SESSION_COUNT)),
            departure_after_session=self.departure_after_session,
        )

    @property
    def agent_count(self) -> int:
        return len(self.agent_session_indices)

    def unsigned_record(self) -> dict[str, object]:
        return {
            "schema_version": STALE_TYPE2_SIDECAR_SCHEMA,
            "uid": self.uid,
            "returning_agent_id": self.returning_agent_id,
            "departure_after_session": self.departure_after_session,
            "return_after_session": self.return_after_session,
            "agent_session_indices": {
                agent: list(indices)
                for agent, indices in sorted(self.agent_session_indices.items())
            },
            "source_record_sha256": self.source_record_sha256,
            "official_record_modified": False,
            "ground_truth_fields_copied": False,
        }

    def record(self) -> dict[str, object]:
        record = self.unsigned_record()
        record["unified_mas"] = unified_mas_episode_record(
            benchmark="STALE-TypeII-Official-MAS-Return",
            episode_id=self.uid,
            assignments=self.agent_session_indices,
            ordered_session_ids=tuple(range(STALE_SESSION_COUNT)),
            departure_after_session=self.departure_after_session,
            return_after_session=self.return_after_session,
        )
        record["episode_sha256"] = canonical_sha256(record)
        return record


def load_stale_type2_records(
    path: Path,
    *,
    expected_file_size: int | None = None,
    expected_file_sha256: str | None = None,
    require_official_counts: bool = False,
) -> tuple[StaleType2Record, ...]:
    path = path.resolve()
    if expected_file_size is not None and path.stat().st_size != expected_file_size:
        raise ValueError("STALE dataset size mismatch")
    if expected_file_sha256 is not None and sha256_path(path) != expected_file_sha256:
        raise ValueError("STALE dataset SHA-256 mismatch")
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, list):
        raise ValueError("official STALE dataset must be a JSON list")
    if require_official_counts and len(payload) != 400:
        raise ValueError("official STALE dataset must contain 400 records")
    records = tuple(
        StaleType2Record.from_record(item)
        for item in payload
        if isinstance(item, Mapping)
        and str(item.get("type") or "").strip().upper() == "T2"
    )
    if len({item.uid for item in records}) != len(records):
        raise ValueError("STALE Type-II UIDs must be unique")
    if require_official_counts and len(records) != STALE_TYPE2_COUNT:
        raise ValueError("official STALE Type-II subset must contain 200 records")
    return records


def load_official_stale_type2(path: Path) -> tuple[StaleType2Record, ...]:
    return load_stale_type2_records(
        path,
        expected_file_size=STALE_DATASET_SIZE,
        expected_file_sha256=STALE_DATASET_SHA256,
        require_official_counts=True,
    )


def build_mas_return_episode(
    record: StaleType2Record,
    *,
    agent_count: int = TASK_AGENT_COUNT,
) -> StaleType2MasReturnEpisode:
    if agent_count != TASK_AGENT_COUNT:
        raise ValueError("unified STALE MAS adapter requires agent_count=5")
    assignments = deterministic_session_assignment(
        tuple(range(STALE_SESSION_COUNT)),
        departure_after_session=record.old_session_index,
    )
    return StaleType2MasReturnEpisode(
        uid=record.uid,
        returning_agent_id=RETURNING_AGENT_ID,
        departure_after_session=record.old_session_index,
        return_after_session=STALE_SESSION_COUNT - 1,
        agent_session_indices=assignments,
        source_record_sha256=record.source_record_sha256,
    )


def actor_views(
    record: StaleType2Record,
    episode: StaleType2MasReturnEpisode,
) -> dict[str, dict[str, object]]:
    if record.uid != episode.uid or record.source_record_sha256 != episode.source_record_sha256:
        raise ValueError("STALE record/sidecar identity mismatch")
    result: dict[str, dict[str, object]] = {}
    for agent, indices in episode.agent_session_indices.items():
        result[agent] = {
            "schema_version": STALE_ACTOR_VIEW_SCHEMA,
            "uid": record.uid,
            "principal_id": agent,
            "lifecycle_phase": (
                "predeparture" if agent == episode.returning_agent_id else "absence"
            ),
            "sessions": [record.actor_session(index) for index in indices],
        }
    return result


def _keys(value: object) -> Iterable[str]:
    if isinstance(value, Mapping):
        for key, item in value.items():
            yield str(key)
            yield from _keys(item)
    elif isinstance(value, Sequence) and not isinstance(value, (str, bytes)):
        for item in value:
            yield from _keys(item)


def leakage_audit(
    record: StaleType2Record,
    episode: StaleType2MasReturnEpisode,
) -> dict[str, object]:
    views = actor_views(record, episode)
    visible_keys = set(_keys(views))
    leaked_keys = sorted(visible_keys & _HIDDEN_KEYS)
    return {
        "schema_version": "stale_type2_actor_leakage_audit_v1",
        "uid": record.uid,
        "passed": not leaked_keys,
        "hidden_annotation_keys_visible": leaked_keys,
        "official_session_count": len(record.sessions),
        "assigned_session_count": sum(
            len(view["sessions"]) for view in views.values()
        ),
        "assigned_exactly_once": len(
            {
                int(session["session_index"])
                for view in views.values()
                for session in view["sessions"]
            }
        )
        == STALE_SESSION_COUNT,
        "actor_view_sha256": {
            agent: canonical_sha256(view) for agent, view in sorted(views.items())
        },
        "evaluator_context_isolated": True,
    }


def build_sidecar_manifest(
    records: Sequence[StaleType2Record],
    *,
    source_path: Path,
    agent_count: int = TASK_AGENT_COUNT,
    require_official_count: bool = True,
) -> dict[str, object]:
    if require_official_count and len(records) != STALE_TYPE2_COUNT:
        raise ValueError("formal Type-II sidecar requires exactly 200 records")
    episodes = tuple(
        build_mas_return_episode(record, agent_count=agent_count)
        for record in records
    )
    unsigned: dict[str, object] = {
        "schema_version": STALE_TYPE2_MANIFEST_SCHEMA,
        "benchmark": "STALE-TypeII-Official-MAS-Return",
        "source": {
            "dataset": "STALEproj/STALE",
            "revision": STALE_DATASET_REVISION,
            "filename": STALE_DATASET_FILENAME,
            "path": str(source_path.resolve()),
            "size_bytes": STALE_DATASET_SIZE,
            "sha256": STALE_DATASET_SHA256,
            "license": "CC-BY-4.0",
        },
        "subset": {"type": "T2", "records": len(records)},
        "execution_protocol": {
            "agent_count": agent_count,
            "returning_agent_id": RETURNING_AGENT_ID,
            "departure_rule": "immediately_after_official_old_evidence_session",
            "return_rule": "after_all_50_official_sessions_before_probing",
            "official_records_modified": False,
            "ground_truth_fields_actor_visible": False,
            "unified_mas_architecture": unified_mas_architecture_record(),
        },
        "episodes": [episode.record() for episode in episodes],
    }
    unsigned["manifest_sha256"] = canonical_sha256(unsigned)
    return unsigned


def load_sidecar_manifest(path: Path) -> tuple[StaleType2MasReturnEpisode, ...]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, Mapping):
        raise ValueError("STALE sidecar manifest must be an object")
    expected = value.get("manifest_sha256")
    unsigned = dict(value)
    unsigned.pop("manifest_sha256", None)
    if expected != canonical_sha256(unsigned):
        raise ValueError("STALE sidecar manifest digest mismatch")
    raw_episodes = value.get("episodes")
    if not isinstance(raw_episodes, Sequence):
        raise ValueError("STALE sidecar manifest requires episodes")
    episodes: list[StaleType2MasReturnEpisode] = []
    for raw in raw_episodes:
        if not isinstance(raw, Mapping):
            raise ValueError("STALE sidecar episode must be an object")
        if raw.get("official_record_modified") is not False:
            raise ValueError("STALE sidecar must declare official_record_modified=false")
        if raw.get("ground_truth_fields_copied") is not False:
            raise ValueError("STALE sidecar must not copy ground-truth fields")
        raw_assignments = raw.get("agent_session_indices")
        if not isinstance(raw_assignments, Mapping):
            raise ValueError("STALE sidecar episode requires agent_session_indices")
        episode = StaleType2MasReturnEpisode(
            uid=_text(raw.get("uid"), "uid"),
            returning_agent_id=_text(
                raw.get("returning_agent_id"), "returning_agent_id"
            ),
            departure_after_session=int(raw["departure_after_session"]),
            return_after_session=int(raw["return_after_session"]),
            agent_session_indices={
                str(agent): tuple(int(index) for index in indices)
                for agent, indices in raw_assignments.items()
                if isinstance(indices, Sequence)
                and not isinstance(indices, (str, bytes))
            },
            source_record_sha256=_text(
                raw.get("source_record_sha256"), "source_record_sha256"
            ),
        )
        if raw.get("episode_sha256") != episode.record()["episode_sha256"]:
            raise ValueError(
                f"STALE sidecar episode digest mismatch: {episode.uid}"
            )
        episodes.append(episode)
    return tuple(episodes)


def bind_records_to_sidecar(
    records: Sequence[StaleType2Record],
    episodes: Sequence[StaleType2MasReturnEpisode],
) -> tuple[tuple[StaleType2Record, StaleType2MasReturnEpisode], ...]:
    """Verify a one-to-one immutable binding between official records and sidecars."""

    record_by_uid = {record.uid: record for record in records}
    if len(record_by_uid) != len(records):
        raise ValueError("STALE records contain duplicate UIDs")
    episode_by_uid = {episode.uid: episode for episode in episodes}
    if len(episode_by_uid) != len(episodes):
        raise ValueError("STALE sidecar contains duplicate UIDs")
    if set(record_by_uid) != set(episode_by_uid):
        raise ValueError("STALE record/sidecar UID sets differ")
    bound: list[tuple[StaleType2Record, StaleType2MasReturnEpisode]] = []
    for record in records:
        episode = episode_by_uid[record.uid]
        if record.source_record_sha256 != episode.source_record_sha256:
            raise ValueError(f"STALE source-record digest mismatch: {record.uid}")
        bound.append((record, episode))
    return tuple(bound)


def official_judge_user_prompt(
    record: StaleType2Record,
    responses: Mapping[str, str],
) -> str:
    answer = record.official_answer_record(responses)["target_model_responses"]
    assert isinstance(answer, Mapping)
    return f"""
[Ground Truth Context]
- M_old: "{record.m_old}"
- M_new: "{record.m_new}"
- Hidden Logic: {record.explanation}

--------------------------------------------------
[Dimension 1: Explicit Probing]
Question 1: {record.queries[0]}
Target Model Response 1: {answer['dim1_response']}

--------------------------------------------------
[Dimension 2: Adversarial Robustness]
Question 2: {record.queries[1]}
Target Model Response 2: {answer['dim2_response']}

--------------------------------------------------
[Dimension 3: Implicit Task]
Question 3: {record.queries[2]}
Target Model Response 3: {answer['dim3_response']}
""".strip()


__all__ = [
    "OFFICIAL_JUDGE_SYSTEM_PROMPT",
    "PROBE_DIMENSIONS",
    "STALE_DATASET_FILENAME",
    "STALE_DATASET_REVISION",
    "STALE_DATASET_SHA256",
    "STALE_DATASET_SIZE",
    "STALE_TYPE2_COUNT",
    "StaleMessage",
    "StaleType2MasReturnEpisode",
    "StaleType2Record",
    "actor_views",
    "bind_records_to_sidecar",
    "build_mas_return_episode",
    "build_sidecar_manifest",
    "canonical_sha256",
    "leakage_audit",
    "load_official_stale_type2",
    "load_sidecar_manifest",
    "load_stale_type2_records",
    "official_judge_user_prompt",
    "sha256_path",
]
